In [2]:
import numpy as np


### algos


Selection Sort: This algorithm segments the list into two parts: sorted and unsorted, and repeatedly selects the smallest (or largest, depending on sorting order) element from the unsorted subarray and moves it to the beginning of the sorted subarray.

Insertion Sort: This algorithm builds a sorted array one item at a time, with each movement a greater value than the key moves one place to the right as the key moves through the array.

Bubble Sort: This simple sorting algorithm repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order, with the pass through the list repeated until the list is sorted.

Quick Sort: This divide-and-conquer algorithm works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays, according to whether they are less than or greater than the pivot, and then recursively applying the method to the sub-arrays.

Merge Sort: This divide-and-conquer algorithm works by dividing the unsorted list into n sublists, each containing one element (a list of one element is considered sorted), and then repeatedly merging sublists to produce new sorted sublists until there is only one sublist remaining.

counting sort: This algorithm works by counting the number of objects having distinct key values (kind of hashing). Then doing some arithmetic to calculate the position of each object in the output sequence.

radix sort: This algorithm sorts the elements by first grouping the individual digits of the same place value. Then, the elements are sorted according to their increasing/decreasing order.

heap sort: This algorithm is a comparison-based sorting technique based on Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end.

### O efficiency of the algorithms

- selection sort: O(n^2)
- bubble sort: O(n^2)
- merge sort: O(n log n)
- quick sort: O(n log n)
- heap sort: O(n log n)
- counting sort: O(n + k)
- radix sort: O(n * k)


In [2]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)


array([1, 2, 3, 4, 5])

In [3]:
def quicksort(x):
    if len(x) <= 1:
        return x
    pivot = x[len(x) // 2]
    left = [i for i in x if i < pivot]
    middle = [i for i in x if i == pivot]
    right = [i for i in x if i > pivot]
    return quicksort(left) + middle + quicksort(right)

x = np.array([2, 1, 4, 3, 5])
quicksort(x)

[1, 2, 3, 4, 5]

In [4]:
def bubblesort(x):
    n = len(x)
    for i in range(n):
        for j in range(0, n-i-1):
            if x[j] > x[j+1]:
                x[j], x[j+1] = x[j+1], x[j]
    return x

x = np.array([2, 1, 4, 3, 5])
bubblesort(x)

array([1, 2, 3, 4, 5])

In [5]:
def insertionsort(x):
    for i in range(1, len(x)):
        j = i
        while j > 0 and x[j] < x[j-1]:
            x[j], x[j-1] = x[j-1], x[j]
            j -= 1
    return x

x = np.array([2, 1, 4, 3, 5])
insertionsort(x)

array([1, 2, 3, 4, 5])

In [12]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        left_half = merge_sort(left_half).copy()
        right_half = merge_sort(right_half).copy()

        i = j = k = 0

        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

    return arr

arr = np.array([2,1,4,3,5])
merge_sort(arr)

array([1, 2, 3, 4, 5])

In [3]:
def counting_sort(arr):
    max_val = max(arr)
    m = max_val + 1
    count = [0] * m

    for a in arr:
        count[a] += 1
    i = 0
    for a in range(m):
        for c in range(count[a]):
            arr[i] = a
            i += 1
    return arr

arr = np.array([2,1,4,3,5])
counting_sort(arr)

array([1, 2, 3, 4, 5])

In [4]:
def radix_sort(arr):
    max_val = max(arr)
    max_exp = len(str(max_val))
    for exp in range(max_exp):
        buckets = [[] for _ in range(10)]
        for i in arr:
            buckets[i // 10**exp % 10].append(i)
        arr = [i for bucket in buckets for i in bucket]
    return arr

arr = np.array([2,1,4,3,5])
radix_sort(arr)

[1, 2, 3, 4, 5]

In [6]:
def heap_sort(arr):
    def heapify(arr, n, i):
        largest = i
        l = 2 * i + 1
        r = 2 * i + 2

        if l < n and arr[i] < arr[l]:
            largest = l

        if r < n and arr[largest] < arr[r]:
            largest = r

        if largest != i:
            arr[i], arr[largest] = arr[largest], arr[i]
            heapify(arr, n, largest)

    n = len(arr)

    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

    return arr

arr = np.array([2,1,4,3,5])
heap_sort(arr)

array([1, 2, 3, 4, 5])

In [5]:
def bucket_sort(arr):
    max_val = max(arr)
    min_val = min(arr)
    n = len(arr)
    num_buckets = 10
    bucket_range = (max_val - min_val) / num_buckets
    buckets = [[] for _ in range(num_buckets)]
    for i in arr:
        buckets[int((i - min_val) // bucket_range)].append(i)
    arr = []
    for bucket in buckets:
        arr.extend(sorted(bucket))
    return arr

arr = np.array([2,1,4,3,5])
bucket_sort(arr)

[1, 2, 3, 4, 5]