In [1]:
import numpy as np

In [2]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [9]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### meta

In [8]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


### accessing array elements

In [10]:
x3[0, 0]

array([8, 1, 5, 9, 8])

In [13]:
x3[0, 1]

array([9, 4, 3, 0, 3])

In [14]:
x3[0, -1]

array([1, 3, 3, 3, 7])

In [12]:
print(x3[0, 1, 2])
x3[0, 1, 2] = 3.14159  # this will be truncated!
print(x3[0, 1, 2])

3
3


### slice

In [3]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x1[1:5:2]

array([1, 3])

In [31]:
x1[5:2:-2]

array([5, 3])

In [32]:
# first  5
x1[:5]

array([0, 1, 2, 3, 4])

In [33]:
# after index 5
x1[5:]

array([5, 6, 7, 8, 9])

In [35]:
# 3rd element to 7th element
x1[2:8]

array([2, 3, 4, 5, 6, 7])

In [36]:
# even elements
x1[::2]

array([0, 2, 4, 6, 8])

In [37]:
# odd elements
x1[1::2]

array([1, 3, 5, 7, 9])

In [38]:
# reverse
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
# reverse every other from index 5
x1[5::-2]

array([5, 3, 1])

In [5]:
x2[0, :]  # first row of x2

array([3, 5, 2, 4])

In [6]:
x2[:, 0]  # first column of x2

array([3, 7, 1])

In [7]:
x2[0]  # equivalent to x2[0,:]

array([3, 5, 2, 4])

In [8]:
# no copy views
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0] = 99
print(x2)

[[3 5]
 [7 6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### copy

In [10]:
x2_copy = x2[:2, :2].copy()
x2_copy[0, 0] = 42
print(x2_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### reshape

In [14]:
grid = np.zeros(10).reshape((10, 1))
print(grid)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [15]:
x = np.array([1, 2, 3])

In [16]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [17]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### concatenation of arrays

In [18]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])  # same dim

array([1, 2, 3, 3, 2, 1])

In [19]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

np.concatenate([grid, grid], axis=1)  # same dim

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [20]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [21]:
# horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### spliting arrays

In [23]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [24]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [26]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### large array

In [7]:
x1 = np.random.randint(10, size=1_000_000_000)
np.sum(x1)

204992266

In [9]:
x1.nbytes / 1e6  # in MB

4000.0