In [1]:
import numpy as np


### algos


Selection Sort: This algorithm segments the list into two parts: sorted and unsorted, and repeatedly selects the smallest (or largest, depending on sorting order) element from the unsorted subarray and moves it to the beginning of the sorted subarray.

Insertion Sort: This algorithm builds a sorted array one item at a time, with each movement a greater value than the key moves one place to the right as the key moves through the array.

Bubble Sort: This simple sorting algorithm repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order, with the pass through the list repeated until the list is sorted.

Quick Sort: This divide-and-conquer algorithm works by selecting a 'pivot' element from the array and partitioning the other elements into two sub-arrays, according to whether they are less than or greater than the pivot, and then recursively applying the method to the sub-arrays.

Merge Sort: This divide-and-conquer algorithm works by dividing the unsorted list into n sublists, each containing one element (a list of one element is considered sorted), and then repeatedly merging sublists to produce new sorted sublists until there is only one sublist remaining.

In [2]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)


array([1, 2, 3, 4, 5])

In [3]:
def quicksort(x):
    if len(x) <= 1:
        return x
    pivot = x[len(x) // 2]
    left = [i for i in x if i < pivot]
    middle = [i for i in x if i == pivot]
    right = [i for i in x if i > pivot]
    return quicksort(left) + middle + quicksort(right)

x = np.array([2, 1, 4, 3, 5])
quicksort(x)

[1, 2, 3, 4, 5]

In [4]:
def bubblesort(x):
    n = len(x)
    for i in range(n):
        for j in range(0, n-i-1):
            if x[j] > x[j+1]:
                x[j], x[j+1] = x[j+1], x[j]
    return x

x = np.array([2, 1, 4, 3, 5])
bubblesort(x)

array([1, 2, 3, 4, 5])

In [5]:
def insertionsort(x):
    for i in range(1, len(x)):
        j = i
        while j > 0 and x[j] < x[j-1]:
            x[j], x[j-1] = x[j-1], x[j]
            j -= 1
    return x

x = np.array([2, 1, 4, 3, 5])
insertionsort(x)

array([1, 2, 3, 4, 5])

In [12]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        left_half = merge_sort(left_half).copy()
        right_half = merge_sort(right_half).copy()

        i = j = k = 0

        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

    return arr

arr = np.array([2,1,4,3,5])
merge_sort(arr)

array([1, 2, 3, 4, 5])

### in np

In [13]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)


[1 0 3 2 4]


In [14]:
x = np.array([3, 1, 4, 2, 5])
i = np.argsort(x)
print(i)


[1 3 0 2 4]


In [15]:
x[i]

array([1, 2, 3, 4, 5])

In [16]:
# by row or by column
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [17]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [18]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### partitioning

In [19]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [20]:
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [21]:
np.partition(X, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

### knn