In [1]:
import numpy as np

In [3]:
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [2]:
# Use a compound data type for structured arrays
data = np.zeros(
    4, dtype={"names": ("name", "age", "weight"), "formats": ("U10", "i4", "f8")}
)
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [4]:
data["name"] = name
data["age"] = age
data["weight"] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [5]:
# Get the name from the last row
data[-1]["name"]

'Doug'

In [6]:
# Get names where age is under 30
data[data["age"] < 30]["name"]

array(['Alice', 'Doug'], dtype='<U10')

### Creating Structured Arrays

In [11]:
_ = np.dtype(
    {"names": ("name", "age", "weight"), "formats": ((np.str_, 10), int, np.float32)}
)
_2 = np.zeros(4, dtype=_)
print(_2.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]


In [8]:
np.dtype([("name", "S10"), ("age", "i4"), ("weight", "f8")])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [9]:
np.dtype("S10,i4,f8")

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

- little endian means the least significant byte is stored first
- big endian means the most significant byte is stored first

In [10]:
tp = np.dtype([("id", "i8"), ("mat", "f8", (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X["mat"][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
